"""User-interface texts in Turkish and English.

UI_LANGUAGE sets the default language ("tr" or "en"); users can switch in the sidebar.
UI_DISCLAIMER replaces the default disclaimer shown above the chat (in every language).
Answers from the assistant follow the language of each question, independent of this setting.
"""

import os
from typing import Any, Dict

LANGUAGES = {"tr": "Türkçe", "en": "English"}
DEFAULT_UI_LANGUAGE = os.getenv("UI_LANGUAGE", "tr") if os.getenv("UI_LANGUAGE", "tr") in LANGUAGES else "tr"
CUSTOM_DISCLAIMER = os.getenv("UI_DISCLAIMER", "").strip()

TEXTS: Dict[str, Dict[str, str]] = {
    # ── General ──
    "language_label": {"tr": "🌐 Dil / Language", "en": "🌐 Language / Dil"},
    "control_panel": {"tr": "⚙️ Kontrol Paneli", "en": "⚙️ Control Panel"},
    "main_title": {"tr": "🏢 OpenLocalRagAgents Asistanı", "en": "🏢 OpenLocalRagAgents Assistant"},
    "subtitle": {
        "tr": "Tamamen kurum içinde çalışan, verileriniz dışarı çıkmayan yapay zekâ asistanı.",
        "en": "Zero-leakage, on-premise generative AI assistant running 100% locally on your infrastructure.",
    },
    "disclaimer": {
        "tr": (
            "⚠️ Cevaplar yapay zekâ tarafından üretilir ve hatalı olabilir. Önemli kararlardan önce kaynak "
            "dokümanı kontrol edin veya ilgili birime danışın."
        ),
        "en": (
            "⚠️ Answers are generated by AI and may be wrong. Check the source document or ask the responsible "
            "office before making important decisions."
        ),
    },
    # ── Login & password ──
    "login_title": {"tr": "🔐 Giriş", "en": "🔐 Enterprise Login"},
    "username": {"tr": "Kullanıcı adı", "en": "Username"},
    "username_placeholder": {"tr": "örn. admin", "en": "e.g., admin"},
    "password": {"tr": "Şifre", "en": "Password"},
    "login_button": {"tr": "Giriş Yap", "en": "Log In"},
    "login_missing": {"tr": "Lütfen kullanıcı adı ve şifre girin.", "en": "Please enter username and password."},
    "login_success": {"tr": "Giriş başarılı!", "en": "Login successful!"},
    "login_failed": {"tr": "Kullanıcı adı veya şifre hatalı.", "en": "Invalid username or password."},
    "connection_error": {"tr": "Bağlantı hatası: {error}", "en": "Connection error: {error}"},
    "logged_in_as": {"tr": "👤 Giriş yapan: **{user}**", "en": "👤 Logged in as: **{user}**"},
    "logout": {"tr": "Çıkış Yap", "en": "Log Out"},
    "change_password_title": {"tr": "🔑 Şifre Değiştir", "en": "🔑 Change Password"},
    "change_password_required": {
        "tr": "Asistanı kullanmadan önce yeni bir şifre belirlemelisiniz.",
        "en": "You must set a new password before using the assistant.",
    },
    "current_password": {"tr": "Mevcut şifre", "en": "Current password"},
    "new_password": {"tr": "Yeni şifre", "en": "New password"},
    "confirm_password": {"tr": "Yeni şifre (tekrar)", "en": "Confirm new password"},
    "update_password": {"tr": "Şifreyi Güncelle", "en": "Update Password"},
    "password_fields_missing": {
        "tr": "Lütfen tüm şifre alanlarını doldurun.",
        "en": "Please fill in all password fields.",
    },
    "password_mismatch": {"tr": "Yeni şifreler eşleşmiyor.", "en": "New passwords do not match."},
    "password_changed": {"tr": "Şifre başarıyla değiştirildi.", "en": "Password changed successfully."},
    "password_change_failed": {"tr": "Şifre değiştirilemedi.", "en": "Password change failed."},
    "auth_required": {
        "tr": "🔒 **Giriş gerekli:** Asistanı kullanmak için kenar çubuğundaki panelden giriş yapın.",
        "en": "🔒 **Authentication Required:** Please log in using the Control Panel in the sidebar to access the Enterprise Assistant.",
    },
    "password_change_pending": {
        "tr": "🔑 **Şifre değişikliği gerekli:** Devam etmek için kenar çubuğundan yeni bir şifre belirleyin.",
        "en": "🔑 **Password Change Required:** Set a new password in the sidebar to continue.",
    },
    # ── System status ──
    "api_connected": {"tr": "🟢 API bağlı", "en": "🟢 API Connected"},
    "api_offline": {"tr": "🔴 API'ye ulaşılamıyor veya oturum süresi doldu", "en": "🔴 API Offline or Session Expired"},
    "start_backend_hint": {
        "tr": "Sunucuyu başlatın: `uvicorn src.main:app`",
        "en": "Start backend: `uvicorn src.main:app`",
    },
    "retrieval_device": {"tr": "**Arama cihazı:**", "en": "**Retrieval device:**"},
    "total_documents": {"tr": "Doküman", "en": "Total Documents"},
    "vector_chunks": {"tr": "Parça", "en": "Vector Chunks"},
    # ── Agents ──
    "agent_team": {"tr": "🤖 Uzman Ajanlar", "en": "🤖 Specialist Agent Team"},
    "active_agent": {"tr": "Aktif ajan:", "en": "Active Specialist Agent:"},
    "active_agent_help": {
        "tr": (
            "Sorunuzu cevaplayacak uzman ajanı seçin. 'Otomatik' modda yönetici ajan sorunuzu inceler ve en "
            "uygun uzmana yönlendirir ya da doğrudan cevaplar."
        ),
        "en": (
            "Select the specialist agent to handle your query. In 'Auto' mode, the Supervisor Agent classifies "
            "intent and delegates to the most appropriate specialist or responds directly."
        ),
    },
    "agent_auto": {"tr": "👑 Otomatik (Yönetici Ajan)", "en": "👑 Auto (Supervisor Orchestrator)"},
    "agent_doc_agent": {"tr": "📄 Doküman Ajanı", "en": "📄 Document & Policy Specialist"},
    "agent_db_agent": {"tr": "🗄️ Veritabanı Ajanı", "en": "🗄️ SQL & Database Analyst"},
    "agent_compliance_agent": {"tr": "🛡️ Uyum Denetçisi", "en": "🛡️ Compliance Auditor"},
    "agent_desc_auto": {
        "tr": "Soruyu inceleyip en uygun uzman ajana yönlendirir veya doğrudan cevaplar.",
        "en": "Analyzes the question and delegates to the best specialist or answers directly.",
    },
    "agent_desc_doc_agent": {
        "tr": "Şirket dokümanlarında arama yapar ve kaynak göstererek cevaplar.",
        "en": "Searches company documents and answers with cited sources.",
    },
    "agent_desc_db_agent": {
        "tr": "Veritabanındaki kayıtları salt okunur SQL sorgularıyla cevaplar.",
        "en": "Answers questions about database records with read-only SQL.",
    },
    "agent_desc_compliance_agent": {
        "tr": "Anlattığınız bir işlemin kurum politikalarına uygun olup olmadığını değerlendirir.",
        "en": "Checks whether an action you describe complies with company policies.",
    },
    # ── Documents ──
    "upload_title": {"tr": "📤 Doküman Yükle", "en": "📤 Upload Document"},
    "upload_label": {"tr": "PDF, Word veya TXT dosyası seçin", "en": "Choose a PDF, Word, or TXT file"},
    "upload_help": {
        "tr": "Yüklenen dosyalar otomatik olarak okunur, parçalara bölünür ve arama indeksine eklenir.",
        "en": "Uploaded files are automatically parsed, chunked, and added to the search index.",
    },
    "upload_button": {"tr": "🚀 Yükle ve İndeksle", "en": "🚀 Upload and Index"},
    "upload_spinner": {"tr": "Doküman işleniyor ve indeksleniyor...", "en": "Parsing and indexing document..."},
    "upload_failed": {"tr": "Yükleme başarısız: {error}", "en": "Upload failed: {error}"},
    "indexed_documents": {"tr": "📚 İndekslenmiş Dokümanlar", "en": "📚 Indexed Documents"},
    "doc_meta": {"tr": "{size} KB | {chunks} parça", "en": "{size} KB | {chunks} chunks"},
    "delete_help": {"tr": "'{name}' dokümanını sil", "en": "Delete '{name}'"},
    "deleted_toast": {"tr": "'{name}' silindi!", "en": "'{name}' deleted!"},
    "no_documents": {"tr": "İndekslenmiş doküman yok.", "en": "No indexed documents found."},
    # ── Database ──
    "database": {"tr": "🗄️ Veritabanı", "en": "🗄️ Database"},
    "db_connected": {"tr": "🟢 **{dialect}** bağlı", "en": "🟢 **{dialect}** Connected"},
    "db_tables": {"tr": "Erişilebilir tablo: {count}", "en": "Accessible Tables: {count}"},
    "select_table": {"tr": "Arama indeksine eklenecek tablo", "en": "Select Table to Vectorize"},
    "vectorize_button": {"tr": "🔄 Tabloyu İndeksle", "en": "🔄 Vectorize Table"},
    "vectorize_spinner": {"tr": "'{table}' tablosu indeksleniyor...", "en": "Vectorizing table '{table}'..."},
    "inspect_schema": {"tr": "🔍 Veritabanı Şemasını İncele", "en": "🔍 Inspect Database Schema"},
    "schema_unavailable": {"tr": "Şema alınamadı.", "en": "Schema unavailable."},
    "db_not_configured": {"tr": "⚪ Veritabanı yapılandırılmamış", "en": "⚪ Database Not Configured"},
    "db_config_hint": {
        "tr": "İsteğe bağlı: PostgreSQL, MSSQL, MySQL, Oracle veya SQLite bağlamak için .env dosyasında DATABASE_URL ayarlayın.",
        "en": "Optional: Set DATABASE_URL in .env to connect PostgreSQL, MSSQL, MySQL, Oracle, or SQLite.",
    },
    "db_offline": {"tr": "⚪ Veritabanına ulaşılamıyor", "en": "⚪ Database Offline"},
    # ── Audit ──
    "audit_trail": {"tr": "🛡️ Denetim Kaydı", "en": "🛡️ Audit Trail"},
    "audit_expander": {"tr": "📋 Kayıtları ve Metrikleri Görüntüle", "en": "📋 View Compliance Logs & Metrics"},
    "metric_total_events": {"tr": "Toplam olay", "en": "Total Events"},
    "metric_queries": {"tr": "Sorgular", "en": "Queries"},
    "metric_stream_queries": {"tr": "Akış sorguları", "en": "Stream Queries"},
    "metric_uploads": {"tr": "Yüklemeler", "en": "Uploads"},
    "metric_logins": {"tr": "Girişler", "en": "Logins"},
    "metric_feedback": {"tr": "Geri bildirim", "en": "Feedback"},
    "latest_activity": {"tr": "**Son etkinlikler:**", "en": "**Latest Activity:**"},
    "no_audit_events": {"tr": "Henüz kayıtlı olay yok.", "en": "No audit events recorded yet."},
    # ── Chat ──
    "welcome": {
        "tr": (
            "Merhaba! Ben kurum içinde çalışan yapay zekâ asistanınızım. Sorularınızı kurumun dokümanlarına, "
            "veritabanlarına ve uyum kurallarına dayanarak cevaplarım."
        ),
        "en": (
            "Hello! I am your enterprise local AI assistant. I can answer questions grounded strictly in your "
            "internal documents, SQL databases, and corporate compliance regulations."
        ),
    },
    "clear_conversation": {"tr": "🧹 Konuşmayı Temizle", "en": "🧹 Clear Conversation"},
    "conversation_cleared": {
        "tr": "Konuşma geçmişi temizlendi. Yeni sorularınızı bekliyorum!",
        "en": "Conversation history cleared. Ready for new questions!",
    },
    "chat_placeholder": {
        "tr": "Dokümanlar, veritabanı veya uyum kuralları hakkında bir soru sorun...",
        "en": "Ask a question about your enterprise documents, database, or compliance...",
    },
    "thinking": {"tr": "💭 Uzman ajanlar sorunuzu inceliyor...", "en": "💭 The agent team is preparing a response..."},
    "no_response": {"tr": "Cevap alınamadı.", "en": "No response received."},
    "session_expired": {
        "tr": "Oturumun süresi doldu. Lütfen tekrar giriş yapın.",
        "en": "Session expired. Please log in again.",
    },
    "api_error": {"tr": "Hata: {error}", "en": "Error: {error}"},
    "api_connection_error": {"tr": "API bağlantı hatası: {error}", "en": "API Connection Error: {error}"},
    "badge_supervisor": {"tr": "👑 Yönetici Ajan (doğrudan cevap)", "en": "👑 Supervisor (Direct Response)"},
    "badge_doc_agent": {"tr": "📄 Doküman Ajanı", "en": "📄 doc_agent (Document RAG Specialist)"},
    "badge_db_agent": {"tr": "🗄️ Veritabanı Ajanı", "en": "🗄️ db_agent (SQL Database Analyst)"},
    "badge_compliance_agent": {"tr": "🛡️ Uyum Denetçisi", "en": "🛡️ compliance_agent (Compliance Auditor)"},
    "trace_title": {"tr": "🔍 Ajan çalışma adımları ({count} adım)", "en": "🔍 Agent Execution Trace ({count} Steps)"},
    "search_query": {"tr": "Arama sorgusu: `{query}`", "en": "Search Query: `{query}`"},
    "audit_refined": {
        "tr": "✍️ *Cevap şirket dokümanlarına göre yeniden değerlendirildi ve düzeltildi.*",
        "en": "✍️ *Response re-evaluated and refined according to company documents.*",
    },
    "audit_verified": {
        "tr": "🛡️ *Cevap şirket dokümanlarıyla doğrulandı.*",
        "en": "🛡️ *Verified directly against company documents.*",
    },
    "audit_unverified": {
        "tr": "⚠️ *Cevap şirket dokümanlarıyla tam olarak doğrulanamadı.*",
        "en": "⚠️ *Could not be fully verified against company documents.*",
    },
    "feedback_up_help": {"tr": "Bu cevap faydalıydı", "en": "This answer was helpful"},
    "feedback_down_help": {"tr": "Bu cevap faydalı değildi", "en": "This answer was not helpful"},
    "feedback_thanks": {"tr": "Geri bildiriminiz için teşekkürler!", "en": "Thank you for your feedback!"},
    "feedback_recorded": {
        "tr": "Geri bildiriminiz kaydedildi, geliştirmek için çalışacağız!",
        "en": "Feedback recorded. We'll work to improve!",
    },
    "sources_title": {"tr": "📚 Kaynaklar ({count} parça)", "en": "📚 Referenced Sources ({count} Chunks)"},
    "page_single": {"tr": "s. {page}", "en": "p. {page}"},
    "page_range": {"tr": "s. {start}–{end}", "en": "pp. {start}–{end}"},
    "chunk": {"tr": "parça #{index}", "en": "chunk #{index}"},
    "score": {"tr": "skor {score}", "en": "score {score}"},
    # ── Generic API messages ──
    "unknown_response": {"tr": "Bilinmeyen yanıt.", "en": "Unknown response."},
    "deleted": {"tr": "Silindi.", "en": "Deleted."},
    "operation_completed": {"tr": "İşlem tamamlandı.", "en": "Operation completed."},
}


def translate(language: str, key: str, **values: Any) -> str:
    """Text for `key` in `language` (Turkish if the language is unknown)."""
    variants = TEXTS[key]
    if key == "disclaimer" and CUSTOM_DISCLAIMER:
        return CUSTOM_DISCLAIMER
    text = variants.get(language, variants["tr"])
    return text.format(**values) if values else text


def page_label(language: str, source: Dict[str, Any]) -> str:
    """'s. 4' / 's. 4–5' for PDF sources with page information, '' otherwise."""
    page = source.get("page")
    if page is None:
        return ""
    end = source.get("page_end")
    if end and end != page:
        return translate(language, "page_range", start=page, end=end)
    return translate(language, "page_single", page=page)
